apiVersion: v1
kind: Service
metadata:
  name: desafiogrupal-k-service
spec:
  selector:
    app: desafiogrupal-k
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
